services:
  postgres: &postgres
    container_name: todo-postgres
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '35432:5432'
    volumes:
      # ref: https://hub.docker.com/_/postgres の `Initialization scripts`
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/log:/etc/postgresql/log
